### ISSUE TITLE
SQLITE3 is NOT loaded! Please install it before proceeding

### ISSUE THREAD

**Issue by GilbN** [linuxserver/docker-organizr#14]
UnRaid

I get this error when I go to www.domain.com/check.php

The chat function does not work because of this.

**Comment by sparklyballs** [comment]
i've just fired up a container 

![screen shot 2017-06-25 at 22 13 15](https://user-images.githubusercontent.com/4343808/27519789-9b0f469c-59f3-11e7-9ee9-d394d319f9db.png)

**Comment by sparklyballs** [comment]
do you have the appdata on the array perhaps ?

**Comment by GilbN** [comment]
Hm, wierd. I even reinstalled the container.

**Comment by GilbN** [comment]
Where can I find that?

**Comment by sparklyballs** [comment]
unraid webui docker tab

**Comment by GilbN** [comment]
Just tested http://192.168.1.34:8282/check.php and its all green now. But if I go to mydomain.com/check.php it says Zip and sqlite not loaded. 

I installed Organizr inside the letsencrypt /www folder

**Comment by sparklyballs** [comment]
sounds like a reverse proxy config rather than a particular problem with anything in this image

@CHBMB you wanna field this one ?

**Comment by CHBMB** [comment]
> I installed Organizr inside the letsencrypt /www folder

What does this mean exactly?  Did you use our organizr docker container or try and install organizr inside our Lets Encrypt container?

**Comment by GilbN** [comment]
My Organizr AppData Config Path is inside the letsencrypt docker /www folder

**Comment by CHBMB** [comment]
Why?

**Comment by GilbN** [comment]
idk, got it to work that way. I'm quite the novice when it comes to this stuff. :p

**Comment by CHBMB** [comment]
The result has probably been that you've overwritten LetsEncrypt config files and neither container will work.

**Comment by GilbN** [comment]
Well everything works. just not the sqlite3 part. Will have to figure out how to do it correct then.

**Comment by CHBMB** [comment]
That's not everything then.....
Install the organizr container.  Install the letsencypt container.  Then reverse proxy the organizr container to access it from WAN.
