### ISSUE TITLE
Curl not enabled error message

### ISSUE THREAD

**Issue by nuentes** [linuxserver/docker-organizr#15]
I have had this installed on my ubuntu 16.10 server for a while. I don't know what I was thinking a couple hours ago, but I clicked Auto Update in Organizr, and all hell has broken loose since then. The page will now only load [this](https://i.imgur.com/yLkOgbm.jpg), and I can't figure out how to get back up and running. I've restarted the container a few times, as well as start/stop, and that has no change. 

`docker logs organizr` results in the following information scrolling forever.

```
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] still could not bind()
```

Things like
```
docker exec organizr service php7 restart
docker exec organizr service nginx restart
docker exec organizr apt-get install php-curl
docker exec organizr sudo apt-get install php-curl
```

all result in `rpc error: code = 2 desc = containerd: container not started`

I apparently don't know enough about docker to get myself out of this mess, and I'm hoping someone here does...
Thanks for any help...

**Comment by aptalca** [comment]
Try recreating the container with the same docker run/create options

To update, you should do a docker pull and then recreate the container

**Comment by nuentes** [comment]
Is there anything that can be done about the current container? I do not want to lose my confguration.

**Comment by CHBMB** [comment]
If you ran with a folder mapped to /config you shouldn't lose your configuration.  That's the whole point.

**Comment by nuentes** [comment]
ok, so yeah, I forgot that I had the config files locally for a second there. So I removed the old instance, and created a new one like so:

```
docker create \
  --name=organizr \
  -v /home/usr/Organizr-config:/config \
  -p 7077:80 \
  lsiocommunity/organizr
```

However, I keep getting the same error message. I then changed the port from 7077 to 7079, thinking maybe there was a conflict, but I keep getting the same thing as the screenshot. I have now removed all the containers (http://192.168.1.219:7077 results in "this site cant be reached"), and added again with the same code as above, and the container installs successfully, but I keep getting the same error message in my browser. What next?

**Comment by CHBMB** [comment]
I'm guessing that when you updated Organizr from the webui that's affected your config files in `/config`

Only thing I can suggest is backup `/config` and make a new fresh install of Organizr then see if you can reinstall your database file (with the container stopped)

Taking a quick look at the structure, the files and folders I'd look at copying back across would be

`/config/www/Dashboard/config/config.php`
`/config/www/users/`
`/config/www/users.db`

If that doesn't work I got no ideas. 

Also there's no `PUID` or `PGID` parameters in your run command which could lead to some permissions issues.

**Comment by nuentes** [comment]
I created a new blank directory, /home/usr/Organizr, and then ran:

```
docker create \
  --name=organizr \
  -v /home/usr/Organizr:/config \
  -p 7077:80 \
  lsiocommunity/organizr
```

I did not copy anything over - I just wanted to test a blank config. I checked, and /home/usr/Organizr now has contents. However, navigating to http://192.168.1.219:7077/ still results in the same error. Realizing it's possibly a permissions issue, I again removed the container and emptied the contents of my testing folder and ran:

```
docker create \
  --name=organizr \
  -v /home/usr/Organizr:/config \
  -e PGID=1000 -e PUID=1000  \
  -p 7077:80 \
  lsiocommunity/organizr
```

1000 being the UID and GID for the owner of the /home/usr/ folder. Still getting the exact same error.

**Comment by CHBMB** [comment]
Try clearing your browser cache then or try a different browser.  Also when the container first starts it needs to pull the config files so it can take a little while.

**Comment by CHBMB** [comment]
Also what are the logs showing with the blank config?

**Comment by nuentes** [comment]
I'm getting the same result across all devices, and all browsers, so it's not a cache issue.

```
usr@NAS:~$ docker create   --name=organizr   -v /home/usr/Organizr:/config   -e PGID=1000 -e PUID=1000    -p 7077:80   lsiocommunity/organizr
29deeb4921cf703db2baf886ce958f6fc07df794b9517479redacted
usr@NAS:~$ docker start organizr
organizr
usr@NAS:~$ docker logs organizr
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-install: executing... 
[cont-init.d] 30-install: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```

**Comment by CHBMB** [comment]
Logs look pristine, I've tested it on my machine and a fresh pull is working, so it's got to be something local to you, but I'm damned if I know what....

**Comment by nuentes** [comment]
well... that's unfortunate...

**Comment by CHBMB** [comment]
Yeah, but unless someone else can think of anything else, I'm out of ideas....

**Comment by nuentes** [comment]
what's the difference between `docker create` and `docker pull`? I was kind of messing around with docker when I first set this up. Is it possible I did a pull, and now it's creating from my orginal pull? I just know that these docker create commands are suspiciously fast.

FYI - I've got no clue what I'm talking about.

**Comment by CHBMB** [comment]
When you do `docker pull` you pull the image
`docker create` will create a container from an image, pulling the image if necessary

`docker ps` will list your containers
`docker images` will list your images

**Comment by nuentes** [comment]
FINALLY.

```
docker rmi lsiocommunity/organizr
docker create \
  --name=organizr \
  -v /home/andre/Organizr-config:/config \
  -e PGID=1000 -e PUID=1000  \
  -p 7077:80 \
  lsiocommunity/organizr
```

this removed the image, pulled a new image, and we're golden. Old config files work just fine. Sorry, and thanks for holding my hand there.

**Comment by CHBMB** [comment]
Glad you got it sorted.
