### ISSUE TITLE
Add path /srv

### ISSUE THREAD

**Issue by Algedi13** [linuxserver/docker-organizr#18]
Hello,

Can you add the possibility to choose path for the folder "www" like / srv and at the same time rename the folder "Dashboard" to "Organizr" please ?

**Comment by sparklyballs** [comment]
not sure what you mean here

do you mean an entry in the site conf or adding to the PATH variable ?

**Comment by Algedi13** [comment]
I use the Caddy container as web server and reverse proxy and I would like to install organizr 'www "in a folder like / srv so that caddy can access it

**Comment by Algedi13** [comment]
Finaly

**Comment by Algedi13** [comment]
Finaly i install directly on www for caddy use. Thanks for your support
