### ISSUE TITLE
Any chance of adding a branch/tag for the v2 beta? 

### ISSUE THREAD

**Issue by adrianocr** [linuxserver/docker-organizr#21]
I run the v2 beta on another machine (normal install -- not docker) and it is very stable. 

The branch is over here: https://github.com/causefx/Organizr/tree/v2-develop

**Comment by homerr** [comment]
It's not routine for us to produce a container based off a dev branch/beta for a product that has a maintained stable release. I appreciate v2.0 may bring extra shiny but I'm sure it won't be long before it's released... sorry
