### ISSUE TITLE
v2 released. Update Dockerfile?

### ISSUE THREAD

**Issue by ryester19** [linuxserver/docker-organizr#29]
It looks like version 2 has officially been released

https://www.reddit.com/r/organizr/comments/aw72wm/organizr_version_20_release_unraid_giveaway/

Any chance of changing the build branch to v2-master?

**Comment by aptalca** [comment]
It would likely take a lot more than just a source branch change.

In any case, nothing to announce at this point other than to say the existing image was always meant to be v1
