### ISSUE TITLE
Broken PHP dependancies

### ISSUE THREAD

**Issue by AllanMar** [linuxserver/docker-organizr#3]
It looks like the base image update has broken this as it uses php7 so the correct session & PDO dependencies are not added by this docker.

**Comment by CHBMB** [comment]
Yeah, we're in the midst of updating/upgrading Alpine & PHP, we haven't formally released this yet.

**Comment by JigSawFr** [comment]
@AllanMar can you fill a pull request with your fork ? (as it's working great again)

**Comment by sparklyballs** [comment]
what does this need to work now ?

i have some minutes.

**Comment by sparklyballs** [comment]
i just copy pasta'd the dependencies from the fork.

new version to the hub.
