### ISSUE TITLE
Images folder not persisted

### ISSUE THREAD

**Issue by apiening** [linuxserver/docker-organizr#35]
The image folder which also holds the uploaded tab icons is not covered by the volume of the `docker-compose.yml` example provided in the the `README.md`.

However this is easy to fix by extending the volume config with an additional entry:
```
    volumes:
      - <path to data>:/config
      - <path to images>:/var/www/html/images
```
(the second volume entry is the one to add)

If the docker images has already been deployed and images has been uploaded, the existing images could be extracted from the running container with:
```
docker cp <container-id>:/var/www/html/images/ <localpath>
```
The container id could be displayed by running `docker ps`.

Maybe the additional volume could be added to the `README.md` file to have a persistent image folder right away.

With kind regards
Andreas

**Comment by nemchik** [comment]
There have been no upstream updates for the v1 branch in over a year. Organizr staff maintains their own image for v2.

https://hub.docker.com/r/organizrtools/organizr-v2

I would recommend having a look at their image.

**Comment by apiening** [comment]
Hi @nemchik,
thank you: I switched to the v2 image as you suggested and everything works right away.
The new version even looks much better to me.

Closing.
