### ISSUE TITLE
API communication issue

### ISSUE THREAD

**Issue by etiennedemoulin** [linuxserver/docker-organizr#36]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
------------------------------

## Expected Behavior
Trying to make a ForwardAuth with traefik and organizr configuration. Overwise I get 404 Not Found nginx/1.14.2 when I connect to https://mydomain.tld/api/?v1/auth&group=1
Organizr web UI is running correctly.

## Here is my current Organizr config
---
version: "2.4"
services:
  organizr:
    image: linuxserver/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /path/to/datas:/config
    ports:
      - 9983:9983
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.organizr-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.organizr-web-secure.entrypoints=web-secured
      - traefik.http.routers.organizr-web-secure.rule=Host(`mydomain.tld`) && PathPrefix(`/`)
      - traefik.http.routers.organizr-web-secure.tls=true
      - traefik.http.routers.organizr-web-secure.tls.certresolver=mytlschallenge
      - traefik.http.routers.organizr-web.entrypoints=web
      - traefik.http.routers.organizr-web.middlewares=organizr-redirect-web-secure
      - traefik.http.routers.organizr-web.rule=Host(`mydomain.tld`) && PathPrefix(`/`)

    restart: unless-stopped

## Environment
**OS:Raspbian**      
**CPU architecture:** armhf      
**How docker service was installed:omv5 configuration**   

## Docker logs
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
GID/UID,
User uid:    1000,
User gid:    1000,

[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-config: executing... ,
[cont-init.d] 20-config: exited 0.,
[cont-init.d] 30-keygen: executing... ,
using keys found in /config/keys,
[cont-init.d] 30-keygen: exited 0.,
[cont-init.d] 50-config: executing... ,
[cont-init.d] 50-config: exited 0.,
[cont-init.d] 99-custom-files: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-files: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.

**Comment by j0nnymoe** [comment]
I would suggest switching to organizr's official image as this is outdated and no longer supported.
