### ISSUE TITLE
Missing PHP7 Package for Update

### ISSUE THREAD

**Issue by JigSawFr** [linuxserver/docker-organizr#4]
It's actually impossible to upgrade du to a missing package:
`php7.0-zip`

You can take a look at this issue:
https://github.com/causefx/Organizr/issues/94

Thank you :)

**Comment by JigSawFr** [comment]
To solve this error and perform update (until docker file is fixed)
- `docker exec -it organizr bash`
- `apk add --no-cache php7.0-zip`
- `reboot`
Container will restart, and package is now installed. You can update Organiz with no problem.

**Comment by causefx** [comment]
@sparklyballs @CHBMB Hi, guys I'm getting ready to release v1.0 either tomorrow or Saturday.  Thank you for creating this docker.  Is it possible to get this docker updated with this zip package?  Will you be moving this off of dev?  if so, would you mind linking me to the correct docker if you do so I can post the link along with the announcement?  Thank you for your time.

**Comment by sparklyballs** [comment]
i've added the package.

as to release, at this stage would probably place this into our lsiocommunity repository

I'll close the issue as the package has been added

**Comment by causefx** [comment]
@sparklyballs awesome, let me know if or when you move it so I can link it :)

thanks for your help.
