### ISSUE TITLE
Missing /var/log/nginx 

### ISSUE THREAD

**Issue by mmoldauer** [linuxserver/docker-organizr#5]
Hello

There is one problem with docker image. _/var/lib/nginx/logs/_ is linked to _/var/log/nginx_ witch is not present in docker image. Manual creation of _/var/log/nginx_ solves the problem till next restart of docker.

Can You please look into?

Docker log full of:
_nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (2: No such file or directory)_

Best Regards

Marek

**Comment by aptalca** [comment]
Did you modify the nginx.conf?

Default nginx.conf tells nginx to log to /config/log/nginx/

**Comment by brhahlen** [comment]
I get the same error, from a freshly pulled docker image.
Didn't modify anything.

**Comment by j0nnymoe** [comment]
Could we get some information on your host os + docker create commands please?

**Comment by brhahlen** [comment]
Of course:
Host OS: CentOS Linux release 7.3.1611 (Core)
Docker create:
```
docker create --name=organizr \
    -v /home/download/CONF/organizr:/config \
    -e PGID=900 -e PUID=1001  \
    -p 7001:80 \
    lsiocommunity/organizr
```

**Comment by j0nnymoe** [comment]
Thanks, when installing docker on centos, did you use the docker in the centos yum repo's or the official docker yum repo? ( https://get.docker.com/ )

**Comment by brhahlen** [comment]
I used the one in the CentOS yum repo.

**Comment by j0nnymoe** [comment]
could you try reinstalling docker from the official repo instead? we have seen in the past the sometimes the version that's in the centos repo can cause issues.

**Comment by sparklyballs** [comment]
can you exec into the container and do the following commands..

`top` and confirm the line for nginx contains `nginx: master process /usr/sbin/nginx -c /config/nginx/nginx.conf`

`ls -lah /config/nginx/`

`cat  /config/nginx/nginx.conf`

`ls -lah /config/nginx/site-confs`

`cat /config/nginx/site-confs/default`

**Comment by brhahlen** [comment]
Installed docker from the official repo, and that seemed to have fixed the issue.
Although I did have to recreate all my containers...

So, running the commands @sparklyballs mentioned is not going to fly.
But, what I did notice is that /var/lib/nginx/logs/ was a broken symlink to /var/log/nginx

**Comment by sparklyballs** [comment]
it doesn't matter (the symlink) if nginx is using the location we specify in our modified nginx.conf.

the centos yum repo version of docker is a menace, lol.

**Comment by j0nnymoe** [comment]
@brhahlen glad you have it working. We've seen this many times previously with centos setups.
